### Create a new Movie (title, releaseDate, genre, rating, price)
POST https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
"title": "Dune",
"releaseDate": "2022-03-29",
"genre": "action",
"rating": "PG-13",
"price": 19.99
}

### Create a new Movie (title, releaseDate, genre, rating, price)
POST https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
  "title": "King Richard",
  "releaseDate": "2022-03-29",
  "genre": "comedy",
  "rating": "PG-13",
  "price": 29.99
}

### Create a new Movie (title, releaseDate, genre, rating, price)
POST https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
  "title": "Turning Red",
  "releaseDate": "2022-02-21",
  "genre": "comedy",
  "rating": "PG",
  "price": 9.99
}

### GET All Movies
GET https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies.json

### GET One Movie by Key
GET https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies/-MzL8Htei18qZt69ajph.json

### UPDATE Movie and change price to 19.98 and genre to action for movie with key -MzL8Htei18qZt69ajph
PUT https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies/-MzL8Htei18qZt69ajph.json
Content-Type: application/json

{
  "title": "Turning Red",
  "releaseDate": "2022-02-21",
  "genre": "action",
  "rating": "PG",
  "price": 19.98
}

### PATCH Movie and change releaseDate to 2022-01-01  for movie with key -MzL8Htei18qZt69ajph
PATCH https://dmit2015-zzhou-fbrtdb-demo-default-rtdb.firebaseio.com/movies/-MzL8Htei18qZt69ajph.json
Content-Type: application/json

{
  "releaseDate": "2022-01-01"
}